<html>
    <body>
        <table>
            <tr>
                <th>Id</th>
                <th>Text</th>
                <th>DateTime</th>
                <th>Active</th>
            </tr>
            <?php
                foreach ($block->getTodoItemCollection() as $key=>$todoItem){
                    echo '<tr>
                            <td>'.$todoItem->getTodoId().'</td>
                            <td>'.$todoItem->getTodoText().'</td>
                            <td>'.$todoItem->getDt().'</td>
                            <td>'.$todoItem->getIsActive().'</td>
                          </tr>';
                }
            ?>
        </table>
    </body>
</html>
